name: CI

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # enable manual execution

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  stack:

    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        stack: ["2.7.5"]
        ghc: ["9.0.2"]

    steps:

    - name: Checkout repo 
      uses: actions/checkout@v2

    - name: Setup Haskell Stack
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
        enable-stack: true

    - name: Cache ~/.stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack${{ matrix.stack }}

    - name: Install dependencies
      run: |
        stack build --system-ghc --test --no-run-tests --only-dependencies

    - name: Run tests with coverage
      run: |
        stack test --system-ghc --test --coverage --fast

    - name: Build
      run: |
        stack build --system-ghc --test --no-run-tests

    - name: Generate coverage report
      uses: 8c6794b6/hpc-codecov-action@v2
      with:
        target: stack:tree-pretty-printer-test
        out: ./codecov.json
        verbose: true

    - name: Send coverage report
      uses: codecov/codecov-action@v2
      with:
        files: ./codecov.json
        fail_ci_if_error: false # optional (default = false)
        verbose: true
